import { IIcon } from '@models/interfaces/icon';
import {
  ArrowIconName,
  BrandIconName,
  DataVIconName,
  EditingIconName,
  EmoticonIconName,
  FinanceIconName,
  FoodDIconName,
  HealthIconName,
  ImagingIconName,
  InterfaceIIconName,
  NatureWIconName,
  NavigationTIconName,
  ObjectTIconName,
  PlaceholderIconName,
  SymbolIconName,
  TechMIconName,
  UserPIconName,
} from '@models/types/icon';

export const ARROWS: Record<ArrowIconName, IIcon> = {
  arrowDown: { library: 'arrows', file: 'arrow-down.svg' },
  arrowDownSm: { library: 'arrows', file: 'arrow-down-sm.svg' },
  arrowLeft: { library: 'arrows', file: 'arrow-left.svg' },
  arrowLeftSm: { library: 'arrows', file: 'arrow-left-sm.svg' },
  arrowRight: { library: 'arrows', file: 'arrow-right.svg' },
  arrowRightSm: { library: 'arrows', file: 'arrow-right-sm.svg' },
  arrowUp: { library: 'arrows', file: 'arrow-up.svg' },
  arrowUpSm: { library: 'arrows', file: 'arrow-up-sm.svg' },
  chevronDown: { library: 'arrows', file: 'chevron-down.svg' },
  chevronDownSm: { library: 'arrows', file: 'chevron-down-sm.svg' },
  chevronLeft: { library: 'arrows', file: 'chevron-left.svg' },
  chevronLeftSm: { library: 'arrows', file: 'chevron-left-sm.svg' },
  chevronRight: { library: 'arrows', file: 'chevron-right.svg' },
  chevronRightSm: { library: 'arrows', file: 'chevron-right-sm.svg' },
  chevronUp: { library: 'arrows', file: 'chevron-up.svg' },
  chevronUpSm: { library: 'arrows', file: 'chevron-up-sm.svg' },
};

export const BRANDS: Record<BrandIconName, IIcon> = {
  adobe: { library: 'brands', file: 'adobe.svg' },
  amazon: { library: 'brands', file: 'amazon.svg' },
  android: { library: 'brands', file: 'android.svg' },
  apple: { library: 'brands', file: 'apple.svg' },
  behance: { library: 'brands', file: 'behance.svg' },
  bitcoin: { library: 'brands', file: 'bitcoin.svg' },
  facebookMessenger: { library: 'brands', file: 'facebook-messenger.svg' },
  facebook: { library: 'brands', file: 'facebook.svg' },
  github: { library: 'brands', file: 'github.svg' },
  googleDrive: { library: 'brands', file: 'google-drive.svg' },
  instagram: { library: 'brands', file: 'instagram.svg' },
  intercom: { library: 'brands', file: 'intercom.svg' },
  linkedin: { library: 'brands', file: 'linkedin.svg' },
  mediumM: { library: 'brands', file: 'medium-m.svg' },
  snapchatGhost: { library: 'brands', file: 'snapchat-ghost.svg' },
  twitter: { library: 'brands', file: 'twitter.svg' },
};

export const DATA_VISUALIZATION: Record<DataVIconName, IIcon> = {
  analysis: { library: 'data-visualization', file: 'analysis.svg' },
  analytics: { library: 'data-visualization', file: 'analytics.svg' },
  arrowGrowth: { library: 'data-visualization', file: 'arrow-growth.svg' },
  chart: { library: 'data-visualization', file: 'chart.svg' },
  chartGrowth: { library: 'data-visualization', file: 'chart-growth.svg' },
  chartLine: { library: 'data-visualization', file: 'chart-line.svg' },
  chartPie: { library: 'data-visualization', file: 'chart-pie.svg' },
  chartPieAlt: { library: 'data-visualization', file: 'chart-pie-alt.svg' },
  graphBar: { library: 'data-visualization', file: 'graph-bar.svg' },
  grid: { library: 'data-visualization', file: 'grid.svg' },
  grids: { library: 'data-visualization', file: 'grids.svg' },
  signalAlt: { library: 'data-visualization', file: 'signal-alt.svg' },
};

export const EDITING: Record<EditingIconName, IIcon> = {
  alignCenterAlt: { library: 'editing', file: 'align-center-alt.svg' },
  alignCenterJustify: { library: 'editing', file: 'align-center-justify.svg' },
  alignCenter: { library: 'editing', file: 'align-center.svg' },
  alignJustify: { library: 'editing', file: 'align-justify.svg' },
  alignLeftJustify: { library: 'editing', file: 'align-left-justify.svg' },
  alignLeft: { library: 'editing', file: 'align-left.svg' },
  alignRightJustify: { library: 'editing', file: 'align-right-justify.svg' },
  alignRight: { library: 'editing', file: 'align-right.svg' },
  horizontalAlignCenter: {
    library: 'editing',
    file: 'horizontal-align-center.svg',
  },
  horizontalAlignLeft: {
    library: 'editing',
    file: 'horizontal-align-left.svg',
  },
  horizontalAlignRight: {
    library: 'editing',
    file: 'horizontal-align-right.svg',
  },
  horizontalDistributionCenter: {
    library: 'editing',
    file: 'horizontal-distribution-center.svg',
  },
  horizontalDistributionLeft: {
    library: 'editing',
    file: 'horizontal-distribution-left.svg',
  },
  horizontalDistributionRight: {
    library: 'editing',
    file: 'horizontal-distribution-right.svg',
  },
};

export const EMOTICON: Record<EmoticonIconName, IIcon> = {
  confused: { library: 'emoticon', file: 'confused.svg' },
  emoji: { library: 'emoticon', file: 'emoji.svg' },
  emojiAngry: { library: 'emoticon', file: 'emoji-angry.svg' },
  emojiAnnoyed: { library: 'emoticon', file: 'emoji-annoyed.svg' },
  emojiAnnoyedAlt: { library: 'emoticon', file: 'emoji-annoyed-alt.svg' },
  emojiGrin: { library: 'emoticon', file: 'emoji-grin.svg' },
  emojiKid: { library: 'emoticon', file: 'emoji-kid.svg' },
  emojiLaughing: { library: 'emoticon', file: 'emoji-laughing.svg' },
  emojiMeh: { library: 'emoticon', file: 'emoji-meh.svg' },
  emojiMehAlt: { library: 'emoticon', file: 'emoji-meh-alt.svg' },
  emojiMehClosedEye: { library: 'emoticon', file: 'emoji-meh-closed-eye.svg' },
  frown: { library: 'emoticon', file: 'frown.svg' },
  sad: { library: 'emoticon', file: 'sad.svg' },
  sick: { library: 'emoticon', file: 'sick.svg' },
  silence: { library: 'emoticon', file: 'silence.svg' },
  silentSquint: { library: 'emoticon', file: 'silent-squint.svg' },
  smile: { library: 'emoticon', file: 'smile.svg' },
  smileBeam: { library: 'emoticon', file: 'smile-beam.svg' },
  smileDizzy: { library: 'emoticon', file: 'smile-dizzy.svg' },
  smileSquintWink: { library: 'emoticon', file: 'smile-squint-wink.svg' },
  smileSquintWinkAlt: {
    library: 'emoticon',
    file: 'smile-squint-wink-alt.svg',
  },
  smileWink: { library: 'emoticon', file: 'smile-wink.svg' },
  smileWinkAlt: { library: 'emoticon', file: 'smile-wink-alt.svg' },
  squint: { library: 'emoticon', file: 'squint.svg' },
  surprise: { library: 'emoticon', file: 'surprise.svg' },
  unamused: { library: 'emoticon', file: 'unamused.svg' },
};

export const FINANCE: Record<FinanceIconName, IIcon> = {
  bill: { library: 'finance', file: 'bill.svg' },
  creditCard: { library: 'finance', file: 'credit-card.svg' },
  dollarAlt: { library: 'finance', file: 'dollar-alt.svg' },
  moneybag: { library: 'finance', file: 'moneybag.svg' },
  usdCircle: { library: 'finance', file: 'usd-circle.svg' },
  usdSquare: { library: 'finance', file: 'usd-square.svg' },
};

export const FOOD_DRINK: Record<FoodDIconName, IIcon> = {
  coffee: { library: 'food-drink', file: 'coffee.svg' },
  crockery: { library: 'food-drink', file: 'crockery.svg' },
  glassMartiniAlt: { library: 'food-drink', file: 'glass-martini-alt.svg' },
  glassMartini: { library: 'food-drink', file: 'glass-martini.svg' },
  glassTea: { library: 'food-drink', file: 'glass-tea.svg' },
  glass: { library: 'food-drink', file: 'glass.svg' },
  pizzaSlice: { library: 'food-drink', file: 'pizza-slice.svg' },
  restaurant: { library: 'food-drink', file: 'restaurant.svg' },
  utensilsAlt: { library: 'food-drink', file: 'utensils-alt.svg' },
  utensils: { library: 'food-drink', file: 'utensils.svg' },
};

export const HEALTH: Record<HealthIconName, IIcon> = {
  bandAid: { library: 'health', file: 'band-aid.svg' },
  dna: { library: 'health', file: 'dna.svg' },
  heartBreak: { library: 'health', file: 'heart-break.svg' },
  heartMedical: { library: 'health', file: 'heart-medical.svg' },
  heartRate: { library: 'health', file: 'heart-rate.svg' },
  heart: { library: 'health', file: 'heart.svg' },
  heartbeat: { library: 'health', file: 'heartbeat.svg' },
  medicalSquare: { library: 'health', file: 'medical-square.svg' },
  medkit: { library: 'health', file: 'medkit.svg' },
  syringe: { library: 'health', file: 'syringe.svg' },
  thermometer: { library: 'health', file: 'thermometer.svg' },
};

export const IMAGING: Record<ImagingIconName, IIcon> = {
  cameraPlus: { library: 'imaging', file: 'camera-plus.svg' },
  cameraReel: { library: 'imaging', file: 'camera-reel.svg' },
  cameraShutter: { library: 'imaging', file: 'camera-shutter.svg' },
  cameraSlash: { library: 'imaging', file: 'camera-slash.svg' },
  camera: { library: 'imaging', file: 'camera.svg' },
  focusAdd: { library: 'imaging', file: 'focus-add.svg' },
  focus: { library: 'imaging', file: 'focus.svg' },
  image: { library: 'imaging', file: 'image.svg' },
  images: { library: 'imaging', file: 'images.svg' },
  videoCamera: { library: 'imaging', file: 'video-camera.svg' },
};

export const INTERFACE_INTERACTION: Record<InterfaceIIconName, IIcon> = {
  airplay: { library: 'interface-interaction', file: 'airplay.svg' },
  archive: { library: 'interface-interaction', file: 'archive.svg' },
  backspace: { library: 'interface-interaction', file: 'backspace.svg' },
  bookmarkFull: {
    library: 'interface-interaction',
    file: 'bookmark-full.svg',
  },
  caretRight: { library: 'interface-interaction', file: 'caret-right.svg' },
  checkCircle: { library: 'interface-interaction', file: 'check-circle.svg' },
  checkSquare: { library: 'interface-interaction', file: 'check-square.svg' },
  check: { library: 'interface-interaction', file: 'check.svg' },
  clearXSolid: {
    library: 'interface-interaction',
    file: 'clear-x-solid.svg',
  },
  clearX: { library: 'interface-interaction', file: 'clear-x.svg' },
  closeExit: { library: 'interface-interaction', file: 'close-exit.svg' },
  cog: { library: 'interface-interaction', file: 'cog.svg' },
  editAlt: { library: 'interface-interaction', file: 'edit-alt.svg' },
  edit: { library: 'interface-interaction', file: 'edit.svg' },
  equalizerAlt: {
    library: 'interface-interaction',
    file: 'equalizer-alt.svg',
  },
  equalizer: { library: 'interface-interaction', file: 'equalizer.svg' },
  expandArrowsAlt: {
    library: 'interface-interaction',
    file: 'expand-arrows-alt.svg',
  },
  externalLinkAlt: {
    library: 'interface-interaction',
    file: 'external-link-alt.svg',
  },
  filter: { library: 'interface-interaction', file: 'filter.svg' },
  grid: { library: 'interface-interaction', file: 'grid.svg' },
  heartAlt: { library: 'interface-interaction', file: 'heart-alt.svg' },
  import: { library: 'interface-interaction', file: 'import.svg' },
  incomingCall: {
    library: 'interface-interaction',
    file: 'incoming-call.svg',
  },
  infoCircle: { library: 'interface-interaction', file: 'info-circle.svg' },
  like: { library: 'interface-interaction', file: 'like.svg' },
  linkAlt: { library: 'interface-interaction', file: 'link-alt.svg' },
  linkH: { library: 'interface-interaction', file: 'link-h.svg' },
  link: { library: 'interface-interaction', file: 'link.svg' },
  listUl: { library: 'interface-interaction', file: 'list-ul.svg' },
  lockAlt: { library: 'interface-interaction', file: 'lock-alt.svg' },
  lockOpenAlt: {
    library: 'interface-interaction',
    file: 'lock-open-alt.svg',
  },
  menuHamburger: {
    library: 'interface-interaction',
    file: 'menu-hamburger.svg',
  },
  menuHorizontal: {
    library: 'interface-interaction',
    file: 'menu-horizontal.svg',
  },
  menu: { library: 'interface-interaction', file: 'menu.svg' },
  message: { library: 'interface-interaction', file: 'message.svg' },
  minus: { library: 'interface-interaction', file: 'minus.svg' },
  paperclip: { library: 'interface-interaction', file: 'paperclip.svg' },
  pen: { library: 'interface-interaction', file: 'pen.svg' },
  plusCircle: { library: 'interface-interaction', file: 'plus-circle.svg' },
  plus: { library: 'interface-interaction', file: 'plus.svg' },
  questionCircle: {
    library: 'interface-interaction',
    file: 'question-circle.svg',
  },
  redo: { library: 'interface-interaction', file: 'redo.svg' },
  repeat: { library: 'interface-interaction', file: 'repeat.svg' },
  resizer: { library: 'interface-interaction', file: 'resizer.svg' },
  searchMinus: { library: 'interface-interaction', file: 'search-minus.svg' },
  searchPlus: { library: 'interface-interaction', file: 'search-plus.svg' },
  search: { library: 'interface-interaction', file: 'search.svg' },
  setting: { library: 'interface-interaction', file: 'setting.svg' },
  shareAlt: { library: 'interface-interaction', file: 'share-alt.svg' },
  signin: { library: 'interface-interaction', file: 'signin.svg' },
  starHalfAlt: {
    library: 'interface-interaction',
    file: 'star-half-alt.svg',
  },
  starSolid: { library: 'interface-interaction', file: 'star-solid.svg' },
  star: { library: 'interface-interaction', file: 'star.svg' },
  sync: { library: 'interface-interaction', file: 'sync.svg' },
  telegramAlt: { library: 'interface-interaction', file: 'telegram-alt.svg' },
  thumbsDown: { library: 'interface-interaction', file: 'thumbs-down.svg' },
  trashAlt: { library: 'interface-interaction', file: 'trash-alt.svg' },
  unlockAlt: { library: 'interface-interaction', file: 'unlock-alt.svg' },
  uploadAlt: { library: 'interface-interaction', file: 'upload-alt.svg' },
  upload: { library: 'interface-interaction', file: 'upload.svg' },
};

export const NATURE_WEATHER: Record<NatureWIconName, IIcon> = {
  cloudDrizzle: { library: 'nature-weather', file: 'cloud-drizzle.svg' },
  cloudMoon: { library: 'nature-weather', file: 'cloud-moon.svg' },
  cloud: { library: 'nature-weather', file: 'cloud.svg' },
  clouds: { library: 'nature-weather', file: 'clouds.svg' },
  desert: { library: 'nature-weather', file: 'desert.svg' },
  flower: { library: 'nature-weather', file: 'flower.svg' },
  kayak: { library: 'nature-weather', file: 'kayak.svg' },
  moon: { library: 'nature-weather', file: 'moon.svg' },
  moonset: { library: 'nature-weather', file: 'moonset.svg' },
  mountainsSun: { library: 'nature-weather', file: 'mountains-sun.svg' },
  mountains: { library: 'nature-weather', file: 'mountains.svg' },
  raindropsAlt: { library: 'nature-weather', file: 'raindrops-alt.svg' },
  snowflake: { library: 'nature-weather', file: 'snowflake.svg' },
  sun: { library: 'nature-weather', file: 'sun.svg' },
  sunset: { library: 'nature-weather', file: 'sunset.svg' },
  temperatureHalf: { library: 'nature-weather', file: 'temperature-half.svg' },
  thunderstorm: { library: 'nature-weather', file: 'thunderstorm.svg' },
  trees: { library: 'nature-weather', file: 'trees.svg' },
  umbrella: { library: 'nature-weather', file: 'umbrella.svg' },
  water: { library: 'nature-weather', file: 'water.svg' },
  windMoon: { library: 'nature-weather', file: 'wind-moon.svg' },
  windSun: { library: 'nature-weather', file: 'wind-sun.svg' },
  wind: { library: 'nature-weather', file: 'wind.svg' },
  world: { library: 'nature-weather', file: 'world.svg' },
};

export const NAVIGATION_TRANSPORT: Record<NavigationTIconName, IIcon> = {
  ambulance: { library: 'navigation-transport', file: 'ambulance.svg' },
  bag: { library: 'navigation-transport', file: 'bag.svg' },
  busAlt: { library: 'navigation-transport', file: 'bus-alt.svg' },
  carSideview: { library: 'navigation-transport', file: 'car-sideview.svg' },
  car: { library: 'navigation-transport', file: 'car.svg' },
  locationPinAlt: {
    library: 'navigation-transport',
    file: 'location-pin-alt.svg',
  },
  locationPoint: {
    library: 'navigation-transport',
    file: 'location-point.svg',
  },
  mapMarkerSlash: {
    library: 'navigation-transport',
    file: 'map-marker-slash.svg',
  },
  mapMarker: { library: 'navigation-transport', file: 'map-marker.svg' },
  mapPinAlt: { library: 'navigation-transport', file: 'map-pin-alt.svg' },
  map: { library: 'navigation-transport', file: 'map.svg' },
  metro: { library: 'navigation-transport', file: 'metro.svg' },
  noEntry: { library: 'navigation-transport', file: 'no-entry.svg' },
  signRight: { library: 'navigation-transport', file: 'sign-right.svg' },
  subwayAlt: { library: 'navigation-transport', file: 'subway-alt.svg' },
  taxi: { library: 'navigation-transport', file: 'taxi.svg' },
  trafficBarrier: {
    library: 'navigation-transport',
    file: 'traffic-barrier.svg',
  },
  truck: { library: 'navigation-transport', file: 'truck.svg' },
};

export const OBJECTS_THINGS: Record<ObjectTIconName, IIcon> = {
  anchor: { library: 'objects-things', file: 'anchor.svg' },
  androidPhoneSlash: {
    library: 'objects-things',
    file: 'android-phone-slash.svg',
  },
  assistiveListeningSystems: {
    library: 'objects-things',
    file: 'assistive-listening-systems.svg',
  },
  babyCarriage: { library: 'objects-things', file: 'baby-carriage.svg' },
  backpack: { library: 'objects-things', file: 'backpack.svg' },
  bagAlt: { library: 'objects-things', file: 'bag-alt.svg' },
  bagSlash: { library: 'objects-things', file: 'bag-slash.svg' },
  balanceScale: { library: 'objects-things', file: 'balance-scale.svg' },
  baseballBall: { library: 'objects-things', file: 'baseball-ball.svg' },
  basketball: { library: 'objects-things', file: 'basketball.svg' },
  bath: { library: 'objects-things', file: 'bath.svg' },
  bedDouble: { library: 'objects-things', file: 'bed-double.svg' },
  bed: { library: 'objects-things', file: 'bed.svg' },
  bell: { library: 'objects-things', file: 'bell.svg' },
  bookAlt: { library: 'objects-things', file: 'book-alt.svg' },
  bookOpen: { library: 'objects-things', file: 'book-open.svg' },
  books: { library: 'objects-things', file: 'books.svg' },
  bowlingBall: { library: 'objects-things', file: 'bowling-ball.svg' },
  box: { library: 'objects-things', file: 'box.svg' },
  briefcaseAlt: { library: 'objects-things', file: 'briefcase-alt.svg' },
  brightness: { library: 'objects-things', file: 'brightness.svg' },
  brushAlt: { library: 'objects-things', file: 'brush-alt.svg' },
  bug: { library: 'objects-things', file: 'bug.svg' },
  building: { library: 'objects-things', file: 'building.svg' },
  calculator: { library: 'objects-things', file: 'calculator.svg' },
  calendarAlt: { library: 'objects-things', file: 'calendar-alt.svg' },
  calender: { library: 'objects-things', file: 'calender.svg' },
  capsule: { library: 'objects-things', file: 'capsule.svg' },
  cardAtm: { library: 'objects-things', file: 'card-atm.svg' },
  circle: { library: 'objects-things', file: 'circle.svg' },
  clockEight: { library: 'objects-things', file: 'clock-eight.svg' },
  commentAltDots: { library: 'objects-things', file: 'comment-alt-dots.svg' },
  commentAltMessage: {
    library: 'objects-things',
    file: 'comment-alt-message.svg',
  },
  cube: { library: 'objects-things', file: 'cube.svg' },
  diamond: { library: 'objects-things', file: 'diamond.svg' },
  drill: { library: 'objects-things', file: 'drill.svg' },
  ear: { library: 'objects-things', file: 'ear.svg' },
  flask: { library: 'objects-things', file: 'flask.svg' },
  footballAmerican: {
    library: 'objects-things',
    file: 'football-american.svg',
  },
  football: { library: 'objects-things', file: 'football.svg' },
  gift: { library: 'objects-things', file: 'gift.svg' },
  glassMartiniAltSlash: {
    library: 'objects-things',
    file: 'glass-martini-alt-slash.svg',
  },
  graduationCap: { library: 'objects-things', file: 'graduation-cap.svg' },
  headphonesAlt: { library: 'objects-things', file: 'headphones-alt.svg' },
  headphones: { library: 'objects-things', file: 'headphones.svg' },
  history: { library: 'objects-things', file: 'history.svg' },
  home3: { library: 'objects-things', file: 'home-3.svg' },
  homeAlt: { library: 'objects-things', file: 'home-alt.svg' },
  home: { library: 'objects-things', file: 'home.svg' },
  hourglass: { library: 'objects-things', file: 'hourglass.svg' },
  keySkeletonAlt: { library: 'objects-things', file: 'key-skeleton-alt.svg' },
  keyboardAlt: { library: 'objects-things', file: 'keyboard-alt.svg' },
  lamp: { library: 'objects-things', file: 'lamp.svg' },
  layerGroup: { library: 'objects-things', file: 'layer-group.svg' },
  lifeRing: { library: 'objects-things', file: 'life-ring.svg' },
  lightbulbAlt: { library: 'objects-things', file: 'lightbulb-alt.svg' },
  mailbox: { library: 'objects-things', file: 'mailbox.svg' },
  moneyBill: { library: 'objects-things', file: 'money-bill.svg' },
  padlock: { library: 'objects-things', file: 'padlock.svg' },
  percentage: { library: 'objects-things', file: 'percentage.svg' },
  phoneAlt: { library: 'objects-things', file: 'phone-alt.svg' },
  phone: { library: 'objects-things', file: 'phone.svg' },
  planeDeparture: { library: 'objects-things', file: 'plane-departure.svg' },
  plane: { library: 'objects-things', file: 'plane.svg' },
  podium: { library: 'objects-things', file: 'podium.svg' },
  prescriptionBottle: {
    library: 'objects-things',
    file: 'prescription-bottle.svg',
  },
  presentationLine: {
    library: 'objects-things',
    file: 'presentation-line.svg',
  },
  priceTagAlt: { library: 'objects-things', file: 'pricetag-alt.svg' },
  pump: { library: 'objects-things', file: 'pump.svg' },
  robot: { library: 'objects-things', file: 'robot.svg' },
  rocket: { library: 'objects-things', file: 'rocket.svg' },
  rulerCombined: { library: 'objects-things', file: 'ruler-combined.svg' },
  ruler: { library: 'objects-things', file: 'ruler.svg' },
  screw: { library: 'objects-things', file: 'screw.svg' },
  ship: { library: 'objects-things', file: 'ship.svg' },
  shoppingBag: { library: 'objects-things', file: 'shopping-bag.svg' },
  shoppingBasket: { library: 'objects-things', file: 'shopping-basket.svg' },
  shoppingCart: { library: 'objects-things', file: 'shopping-cart.svg' },
  square: { library: 'objects-things', file: 'square.svg' },
  storeAlt: { library: 'objects-things', file: 'store-alt.svg' },
  store: { library: 'objects-things', file: 'store.svg' },
  tableTennis: { library: 'objects-things', file: 'table-tennis.svg' },
  table: { library: 'objects-things', file: 'table.svg' },
  tagAlt: { library: 'objects-things', file: 'tag-alt.svg' },
  telescope: { library: 'objects-things', file: 'telescope.svg' },
  tennisBall: { library: 'objects-things', file: 'tennis-ball.svg' },
  ticket: { library: 'objects-things', file: 'ticket.svg' },
  triangle: { library: 'objects-things', file: 'triangle.svg' },
  trophy: { library: 'objects-things', file: 'trophy.svg' },
  university: { library: 'objects-things', file: 'university.svg' },
  volleyball: { library: 'objects-things', file: 'volleyball.svg' },
  wallet: { library: 'objects-things', file: 'wallet.svg' },
  watchAlt: { library: 'objects-things', file: 'watch-alt.svg' },
  watch: { library: 'objects-things', file: 'watch.svg' },
  wheelchairAlt: { library: 'objects-things', file: 'wheelchair-alt.svg' },
};

export const PLACEHOLDERS: Record<PlaceholderIconName, IIcon> = {
  placeholder1: { library: 'placeholders', file: 'placeholder-1.svg' },
  placeholder2: { library: 'placeholders', file: 'placeholder-2.svg' },
  placeholder3: { library: 'placeholders', file: 'placeholder-3.svg' },
};

export const SYMBOLS: Record<SymbolIconName, IIcon> = {
  accessibleIconAlt: { library: 'symbols', file: 'accessible-icon-alt.svg' },
  at: { library: 'symbols', file: 'at.svg' },
  ban: { library: 'symbols', file: 'ban.svg' },
  batteryEmpty: { library: 'symbols', file: 'battery-empty.svg' },
  bluetoothB: { library: 'symbols', file: 'bluetooth-b.svg' },
  boltAlt: { library: 'symbols', file: 'bolt-alt.svg' },
  bolt: { library: 'symbols', file: 'bolt.svg' },
  exclamationCircle: { library: 'symbols', file: 'exclamation-circle.svg' },
  exclamationOctagon: { library: 'symbols', file: 'exclamation-octagon.svg' },
  exclamationTriangle: { library: 'symbols', file: 'exclamation-triangle.svg' },
  eyeSlash: { library: 'symbols', file: 'eye-slash.svg' },
  eye: { library: 'symbols', file: 'eye.svg' },
  globe: { library: 'symbols', file: 'globe.svg' },
  layers: { library: 'symbols', file: 'layers.svg' },
  rssInterface: { library: 'symbols', file: 'rss interface.svg' },
  rss: { library: 'symbols', file: 'rss.svg' },
  shield: { library: 'symbols', file: 'shield.svg' },
  signal: { library: 'symbols', file: 'signal.svg' },
  swimmer: { library: 'symbols', file: 'swimmer.svg' },
  wifi: { library: 'symbols', file: 'wifi.svg' },
};

export const TECH_MEDIA: Record<TechMIconName, IIcon> = {
  autoFlash: { library: 'tech-media', file: 'auto-flash.svg' },
  backward: { library: 'tech-media', file: 'backward.svg' },
  cd: { library: 'tech-media', file: 'cd.svg' },
  clipboardNotes: { library: 'tech-media', file: 'clipboard-notes.svg' },
  copy: { library: 'tech-media', file: 'copy.svg' },
  database: { library: 'tech-media', file: 'database.svg' },
  desktopAlt: { library: 'tech-media', file: 'desktop-alt.svg' },
  desktop: { library: 'tech-media', file: 'desktop.svg' },
  envelopeAlt: { library: 'tech-media', file: 'envelope-alt.svg' },
  envelopes: { library: 'tech-media', file: 'envelopes.svg' },
  fileAlt: { library: 'tech-media', file: 'file-alt.svg' },
  fileBlank: { library: 'tech-media', file: 'file-blank.svg' },
  fileCheck: { library: 'tech-media', file: 'file-check.svg' },
  fileDownload: { library: 'tech-media', file: 'file-download.svg' },
  flash: { library: 'tech-media', file: 'flash.svg' },
  folderOpen: { library: 'tech-media', file: 'folder-open.svg' },
  folder: { library: 'tech-media', file: 'folder.svg' },
  forward: { library: 'tech-media', file: 'forward.svg' },
  laptop: { library: 'tech-media', file: 'laptop.svg' },
  message: { library: 'tech-media', file: 'message.svg' },
  microphone: { library: 'tech-media', file: 'microphone.svg' },
  mobileAndroid: { library: 'tech-media', file: 'mobile-android.svg' },
  monitor: { library: 'tech-media', file: 'monitor.svg' },
  mouseAlt: { library: 'tech-media', file: 'mouse-alt.svg' },
  musicSign: { library: 'tech-media', file: 'music-sign.svg' },
  musicTune: { library: 'tech-media', file: 'music-tune.svg' },
  mute: { library: 'tech-media', file: 'mute.svg' },
  noFlash: { library: 'tech-media', file: 'no-flash.svg' },
  notAllowMusic: { library: 'tech-media', file: 'not-allow-music.svg' },
  notes: { library: 'tech-media', file: 'notes.svg' },
  pauseCircle: { library: 'tech-media', file: 'pause-circle.svg' },
  pause: { library: 'tech-media', file: 'pause.svg' },
  photo: { library: 'tech-media', file: 'photo.svg' },
  playAlt: { library: 'tech-media', file: 'play-alt.svg' },
  play: { library: 'tech-media', file: 'play.svg' },
  postcard: { library: 'tech-media', file: 'postcard.svg' },
  print: { library: 'tech-media', file: 'print.svg' },
  receiptAlt: { library: 'tech-media', file: 'receipt-alt.svg' },
  record: { library: 'tech-media', file: 'record.svg' },
  save: { library: 'tech-media', file: 'save.svg' },
  serverAlt: { library: 'tech-media', file: 'server-alt.svg' },
  serverConnection: { library: 'tech-media', file: 'server-connection.svg' },
  serverNetworkAlt: { library: 'tech-media', file: 'server-network-alt.svg' },
  serverNetwork: { library: 'tech-media', file: 'server-network.svg' },
  server: { library: 'tech-media', file: 'server.svg' },
  servers: { library: 'tech-media', file: 'servers.svg' },
  shutterAlt: { library: 'tech-media', file: 'shutter-alt.svg' },
  sitemap: { library: 'tech-media', file: 'sitemap.svg' },
  skipBack: { library: 'tech-media', file: 'skip-back.svg' },
  skipBackCircle: { library: 'tech-media', file: 'skip-back-circle.svg' },
  skipBackAlt: { library: 'tech-media', file: 'skip-back-alt.svg' },
  skipForwardAlt: { library: 'tech-media', file: 'skip-forward-alt.svg' },
  skipForwardCircle: { library: 'tech-media', file: 'skip-forward-circle.svg' },
  skipForward: { library: 'tech-media', file: 'skip-forward.svg' },
  stepBackward: { library: 'tech-media', file: 'step-backward.svg' },
  stepForward: { library: 'tech-media', file: 'step-forward.svg' },
  stopCircle: { library: 'tech-media', file: 'stop-circle.svg' },
  tabManager: { library: 'tech-media', file: 'tab-manager.svg' },
  tablet: { library: 'tech-media', file: 'tablet.svg' },
  voicemailRectangle: { library: 'tech-media', file: 'voicemail-rectangle.svg' },
  voicemail: { library: 'tech-media', file: 'voicemail.svg' },
  volumeMute: { library: 'tech-media', file: 'volume-mute.svg' },
  volumeOff: { library: 'tech-media', file: 'volume-off.svg' },
  volume: { library: 'tech-media', file: 'volume.svg' },
  window: { library: 'tech-media', file: 'window.svg' },
};

export const USERS_PEOPLE: Record<UserPIconName, IIcon> = {
  constructionWorker: { library: 'users-people', file: 'construction-worker.svg' },
  userAdd: { library: 'users-people', file: 'user-add.svg' },
  userCircle: { library: 'users-people', file: 'user-circle.svg' },
  userLike: { library: 'users-people', file: 'user-like.svg' },
  userSquare: { library: 'users-people', file: 'user-square.svg' },
  user: { library: 'users-people', file: 'user.svg' },
  users: { library: 'users-people', file: 'users.svg' },
};
